services:
  root:
    build:
      context: ./projects/root
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./projects/root:/app
      - /app/node_modules
    networks:
      - bytebank_network
    depends_on:
      - util-ui
      - util-api
      - app-header
      - app-dashboard
      - app-transactions

  app-header:
    build:
      context: ./projects/app-header
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./projects/app-header:/app
      - /app/node_modules
    networks:
      - bytebank_network
    depends_on:
      - util-ui
      - util-api

  app-dashboard:
    build:
      context: ./projects/app-dashboard
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./projects/app-dashboard:/app
      - /app/node_modules
    networks:
      - bytebank_network

  app-transactions:
    build:
      context: ./projects/app-transactions
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./projects/app-transactions:/app
      - /app/node_modules
    networks:
      - bytebank_network

  util-ui:
    build:
      context: ./projects/util-ui
      dockerfile: Dockerfile
    ports:
      - "8310:8310"
    volumes:
      - ./projects/util-ui:/app
      - /app/node_modules
    networks:
      - bytebank_network

  util-api:
    build:
      context: ./projects/util-api
      dockerfile: Dockerfile
    ports:
      - "8311:8311"
    volumes:
      - ./projects/util-api:/app
      - /app/node_modules
    networks:
      - bytebank_network

networks:
  bytebank_network:
    driver: bridge
