services:
  root:
    build:
      context: ./projects/root
    ports:
      - "3000:3000"
    volumes:
      - ./projects/root:/app
      - /app/node_modules
    networks:
      - bytebank_network
    depends_on:
      - app-header
      - app-dashboard
      # - app-transaction

  app-header:
    build:
      context: ./projects/app-header
    ports:
      - "3001:3001"
    volumes:
      - ./projects/app-header:/app
      - /app/node_modules
      # - ./projects/api-client:/app/node_modules/@bytebank/api-client
    networks:
      - bytebank_network

  app-dashboard:
    build:
      context: ./projects/app-dashboard
    ports:
      - "3002:3002"
    volumes:
      - ./projects/app-dashboard:/app
      - /app/node_modules
    networks:
      - bytebank_network

  util-ui:
    build:
      context: ./projects/util-ui
    ports:
      - "8310:8310"
    volumes:
      - ./projects/util-ui:/app
      - /app/node_modules
    networks:
      - bytebank_network

networks:
  bytebank_network:
    driver: bridge
